[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[flake8]
ignore = [ "E203", "E266", "E501", "W503", "F403", "F401"]
exclude = [ ".git", "__pycache__", "env", "venv" ]
max-line-length = 100
max-complexity = 18
select = ["B","C","E","F","W","T4","B9"]
