# Generated by Django 5.2.4 on 2025-10-26 23:31

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dsh', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\s\\-()]+$', message='Invalid phone number')])),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=7)),
                ('status', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='created', max_length=50)),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('date_delivered', models.DateTimeField(blank=True, null=True)),
                ('status_pay', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('partly_paid', 'partly_paid'), ('rejected', 'rejected'), ('refunded', 'refunded')], default='pending', max_length=20)),
                ('street_home', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dsh_payment.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dsh.product')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=50)),
                ('status_pay', models.CharField(blank=True, choices=[('pending', 'pending'), ('paid', 'paid'), ('partly_paid', 'partly_paid'), ('rejected', 'rejected'), ('refunded', 'refunded')], max_length=30, null=True)),
                ('amount_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('status_time', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dsh_payment.order')),
            ],
        ),
    ]
