# Generated by Django 5.2.4 on 2025-10-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered')], max_length=50),
        ),
    ]
