# Generated by Django 5.2.4 on 2025-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_payment', '0002_alter_order_status_alter_orderlog_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_state',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_street_home',
            new_name='street_home',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], default='created', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('canceled', 'canceled')], max_length=50),
        ),
    ]
