# Generated by Django 5.2.4 on 2025-10-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_payment', '0003_rename_delivery_city_order_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='code',
            new_name='zipcode',
        ),
    ]
