# Generated by Django 5.2.4 on 2025-10-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_payment', '0004_rename_code_order_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_pay',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('partly_paid', 'partly_paid'), ('rejected', 'rejected'), ('refunded', ' refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='orderlog',
            name='status_pay',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('paid', 'paid'), ('partly_paid', 'partly_paid'), ('rejected', 'rejected'), ('refunded', ' refunded')], max_length=30, null=True),
        ),
    ]
