# Generated by Django 5.2.4 on 2025-10-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsh_payment', '0005_order_status_pay_orderlog_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
