# Generated by Django 5.2.4 on 2025-08-01 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale_prise',
            new_name='sale_price',
        ),
    ]
