# Generated by Django 5.2.4 on 2025-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0003_product_article_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
