# Generated by Django 5.2.4 on 2025-09-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0004_alter_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
