# Generated by Django 5.2.4 on 2025-10-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0005_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('shipped', 'shipped'), ('delivered', 'delivered'), ('cancelled', 'cancelled')], default='pending', max_length=20),
        ),
    ]
