# Generated by Django 5.2.4 on 2025-10-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0007_product_allow_backorder_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
