# Generated by Django 5.2.4 on 2025-10-19 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dsh', '0008_remove_order_user_remove_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allow_backorder',
        ),
    ]
